name: 添加RSS源
about: 提交新的RSS源，自动添加到监控列表
title: "添加RSS源："
labels: ["add-rss"]  # 修复：labels应该是数组，而不是字符串
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        请按照以下格式提交RSS源，系统会自动处理并添加到监控列表。
        感谢您的贡献！

  - type: input
    id: website-name
    attributes:
      label: 网站名称
      description: 请输入网站的名称
      placeholder: 例如：奇安信威胁情报中心
    validations:
      required: true

  - type: input
    id: rss-url
    attributes:
      label: RSS URL
      description: 请输入网站的RSS订阅地址
      placeholder: 例如：https://example.com/feed.xml
    validations:
      required: true
      pattern: ^https?://.*

  - type: textarea
    id: description
    attributes:
      label: 描述（可选）
      description: 可以添加网站的描述信息
      placeholder: 这是一个安全资讯网站，提供最新的漏洞和威胁情报

  - type: checkboxes
    id: terms
    attributes:
      label: 确认信息
      description: 请确认以下信息
      options:
        - label: 我已确认该RSS源可以正常访问
          required: true
        - label: 我已确认该RSS源内容合法合规
          required: true
        - label: 我已确认该RSS源定期更新
          required: true